// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialNetworkApi.Core.Data;

#nullable disable

namespace SocialNetworkApi.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220611200712_v1.0.0")]
    partial class v100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SocialNetworkApi.Core.Entities.ApplicationRol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("ApplicationRol");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RolId = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("SocialNetworkApi.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@mail.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            PasswordHash = "$2a$11$DANETUu7Ygt5FdeKsYKHe.7ZJdV.tCNrakdypwkiTqzxPxOEzpGQK",
                            RolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "blowe@mail.com",
                            FirstName = "Barrett",
                            Gender = "MASC",
                            LastName = "Lowe",
                            PasswordHash = "$2a$11$ULBWj1lVeB0WqT3pfEXqeOf5zlvC4TkLH/IyvcmPYGGDdbX0IT/UC",
                            RolId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "cdisney@mail.com",
                            FirstName = "Curtis",
                            Gender = "MASC",
                            LastName = "Disney",
                            PasswordHash = "$2a$11$C7gKRmurmSbZ8mOPTxOl5ul3RwtENueoM0ocx6lz9vISjNZNjGt0.",
                            RolId = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "sowston@mail.com",
                            FirstName = "Stafford",
                            Gender = "MASC",
                            LastName = "Owston",
                            PasswordHash = "$2a$11$W4lpMnJU7FUS2nLi6OF9LuU0mlh0ekAKGnelb/bqPHATCoGMpSyD.",
                            RolId = 2
                        },
                        new
                        {
                            Id = 5,
                            Email = "klowe@mail.com",
                            FirstName = "Kira",
                            Gender = "FEM",
                            LastName = "Lowe",
                            PasswordHash = "$2a$11$UB6B3c2iNJpqrkFTvb2fu./UFTJHcN07qhv/QbntQyQ2AnytIgDQC",
                            RolId = 2
                        },
                        new
                        {
                            Id = 6,
                            Email = "khaward@mail.com",
                            FirstName = "Kira",
                            Gender = "FEM",
                            LastName = "Haward",
                            PasswordHash = "$2a$11$YGdIJnhZXbVsCJZoK3MLyOZH9Yeh0HvVqMw3UUVuf44eJ0B50o2bS",
                            RolId = 2
                        },
                        new
                        {
                            Id = 7,
                            Email = "rlowe@mail.com",
                            FirstName = "Ronda",
                            Gender = "FEM",
                            LastName = "Lowe",
                            PasswordHash = "$2a$11$Uu.oY5pj5qjPlKlWQtlj2u8d8nPnT2I4HNPEZHNDyp2owed3LdOWq",
                            RolId = 2
                        },
                        new
                        {
                            Id = 8,
                            Email = "esweet@mail.com",
                            FirstName = "Everett",
                            Gender = "MASC",
                            LastName = "Sweet",
                            PasswordHash = "$2a$11$wK5QWbD4eyR/Ca2VCgnvAOmpzl0Mjj8OLMRRynb7df7BC5M8.uWQm",
                            RolId = 2
                        },
                        new
                        {
                            Id = 9,
                            Email = "dnicolson@mail.com",
                            FirstName = "Doyle",
                            Gender = "MASC",
                            LastName = "Nicolson",
                            PasswordHash = "$2a$11$D9Ku.2LFIAXd6WW3Cq1WRupjEFKpuTt/wbL.2zUPE0T3OOXmSMaCe",
                            RolId = 2
                        },
                        new
                        {
                            Id = 10,
                            Email = "pclaus@mail.com",
                            FirstName = "Pablo",
                            Gender = "MASC",
                            LastName = "Claus",
                            PasswordHash = "$2a$11$Yazv0zi/vZPV7Jwy2ZO9oOE7kniPBaDWaDKDlDNj3z08EKCd7FJwq",
                            RolId = 2
                        });
                });

            modelBuilder.Entity("SocialNetworkApi.Core.Entities.ApplicationUser", b =>
                {
                    b.HasOne("SocialNetworkApi.Core.Entities.ApplicationRol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
