// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialNetworkApi.Core.Data;

#nullable disable

namespace SocialNetworkApi.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SocialNetworkApi.Core.Entities.ApplicationRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("ApplicationRole");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("SocialNetworkApi.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@mail.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            PasswordHash = "$2a$11$L24W9Z4GOi1EP4.jdmEy/uCi0c/RYPHadaosM8V4pMsn8mL6FulCe",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "blowe@mail.com",
                            FirstName = "Barrett",
                            Gender = "MASC",
                            LastName = "Lowe",
                            PasswordHash = "$2a$11$w5UVe1vts0adJvQ4mlQYS.51GrrYSC8Bkvq1iCh/BHVWZhy/DWpE6",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "cdisney@mail.com",
                            FirstName = "Curtis",
                            Gender = "MASC",
                            LastName = "Disney",
                            PasswordHash = "$2a$11$Y2DpH/LMMLK598cnPxu2kO95peKXIFIvpEzktwK8Wf/Nyvmh0Bskq",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "sowston@mail.com",
                            FirstName = "Stafford",
                            Gender = "MASC",
                            LastName = "Owston",
                            PasswordHash = "$2a$11$jdLtz.u2PF0JAwanF1O9Kei5FtCtLPh61km0g7C5pSf3hsrwm/Ff.",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            Email = "klowe@mail.com",
                            FirstName = "Kira",
                            Gender = "FEM",
                            LastName = "Lowe",
                            PasswordHash = "$2a$11$dUQznXUI/RGI3WH6zOKVlu8j8OGXwpcHHMDT9LUzSnFwJhwKdI8ci",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            Email = "khaward@mail.com",
                            FirstName = "Kira",
                            Gender = "FEM",
                            LastName = "Haward",
                            PasswordHash = "$2a$11$DgKMw45peEpj2Ej9QlUjPuTzv1Bo1UWyQ4zg883udwELyZAu3DxzC",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            Email = "rlowe@mail.com",
                            FirstName = "Ronda",
                            Gender = "FEM",
                            LastName = "Lowe",
                            PasswordHash = "$2a$11$pcKPJnix6UYra4RHJh2GXufg7LyMh2tuOQAzAu6Knxj/vIb5M9GaC",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            Email = "esweet@mail.com",
                            FirstName = "Everett",
                            Gender = "MASC",
                            LastName = "Sweet",
                            PasswordHash = "$2a$11$FJ2Jxh/p0puKkA/SbVZur.G6Y6t54/pMWiG5wfU0uqG2YEbDU5UlO",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            Email = "dnicolson@mail.com",
                            FirstName = "Doyle",
                            Gender = "MASC",
                            LastName = "Nicolson",
                            PasswordHash = "$2a$11$EZsCROPtRlxdoGz742S4POHBMqsbZ72Anpl62VE0oB1GlI4nh5ju2",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            Email = "pclaus@mail.com",
                            FirstName = "Pablo",
                            Gender = "MASC",
                            LastName = "Claus",
                            PasswordHash = "$2a$11$d8Q5N2FmIbsrb/k2OEMvDeqOtLRHoeoUTr7XS0NUVfBkYMDQmX0G2",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("SocialNetworkApi.Core.Entities.ApplicationUser", b =>
                {
                    b.HasOne("SocialNetworkApi.Core.Entities.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
